# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Eventrr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  # Pods for Eventrr

  target 'EventrrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventrrUITests' do
    # Pods for testing
  end

end
